bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: HmQd98uQAwe4H7d1RHx7uWAauVtVXO593yUb4e6Dq/vaX6v+GPDBvI3bFiSaY//p0NgZn0HjNuhqz2rjYvp5dIe0zdOQ2DsIcz4qDRaBG4FU3LedW1gF3ms8Lpj/w9xlqM82FOWwmBJbgDM4HGx852vdT3s3kutRpjgh8bE8ErSpyn6GbC1wzFF5c5byPhOFMpW6yOvTF+o+Jiq2NnzT1zW4IHtR02idZ17dUmA54VBes0MfWeO/qmeacBkoOmRoXKwxjOAGhg/OMRZKhAmtufbwjIKYEz9UOrITLVOmobG8wxDEYGpjuPHkukhQ+lbN4vRwXjM+qPUfs/i7t/0QBC3lh2TXpJO+POJRNHJzsDb6z3/TqzeqTu621AUuNyF7lMWsB9fUj/ef9po5KCVr5b1HyZdW8Sl7dMlvdlr5xUHftXvHBvKtVFBeWYjJ3cy7/p1L64jsBOVs6iZmpucg57yq86dPXLXSzM0Kfj5dCW3cryuE+bquNYeGLXz4UszPQofhXLmd3yhMkptKghk0Umsqq3WQu20qlha9HaY8XUWnPsjg6fIluDJm5yp5rngR5Na2Xo2aMrXVXVGu8QULaUnjavrm25R/2Q7R436/EwqLdiHh0/r6Z5CesStyXCKDMhYSYAeZSqFLuPvDyxFR0MqWECI/T8+g5r9UbpkcQBU=
conda_forge_output_validation: false
